name: Deploy

on:
  push:
    branches:
      - main
  pull_request:
    branches: [main]
    types: [opened, synchronize]


jobs:
  simple_deployment_pipeline:
      runs-on: ubuntu-18.04
      env: 
        MONGODB_URI: ${{ secrets.MONGODB_URI }} 
        MONGODB_URI_TEST: ${{secrets.MONGODB_URI_TEST}}
        SECRET: ${{secrets.SECRET}}
      steps:
        - uses: actions/checkout@v2
        - uses: actions/setup-node@v1
          with:
            node-version: '12.x'
        - name: npm install 
          run: npm install && cd client && npm install
        - name: lint front-end
          run: npm run lint:client
        - name: lint back-end
          run: npm run lint
        - name: build
          run: npm run build
        - name: front-end testing
          run: npm run test:client
        - name: back-end testing
          run: npm run test
        - name: e2e tests
          uses: cypress-io/github-action@v2
          with:
            command: npm run test:e2e
            start: npm run start:test
            wait-on: http://localhost:3001
        - name: deploy
          if: ${{ github.event_name == 'push' && !contains(join(github.event.commits.*.message, ' '), '#skip')}}
          uses: akhileshns/heroku-deploy@v3.12.12 
          with:
            heroku_api_key: ${{secrets.HEROKU_API_KEY}}
            heroku_app_name: "part11fsobloglist" 
            heroku_email: "atukadagio123@gmail.com"
            healthcheck: "https://part11fsobloglist.herokuapp.com/health"
            checkstring: "ok"
            rollbackonhealthcheckfailed: true
          env:
            MONGODB_URI: ${{ secrets.MONGODB_URI }}
            SECRET: ${{secrets.SECRET}}
            
